pipeline {
    agent any
    stages {

        stage('Test') {
            steps {
                dir('complete') {
                    sh 'mvn test'
                }
            }
        }

        stage('Build') {
            steps {
                dir('complete') {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('complete') {
                    sh "docker build -t messaoudiachraf/spring-demo:${BUILD_NUMBER} ."
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh "docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}"
                    sh "docker push messaoudiachraf/spring-demo:${BUILD_NUMBER}"
                }
            }
        }

        stage('Update Manifest') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'github-credentials',
                    usernameVariable: 'GIT_USER',
                    passwordVariable: 'GIT_PASS'
                )]) {
                    sh """
                        rm -rf spring-demo-manifests
                        git clone https://${GIT_USER}:${GIT_PASS}@github.com/messaoudi-achraf/spring-demo-manifests.git
                        cd spring-demo-manifests
                        sed -i 's|image: messaoudiachraf/spring-demo:.*|image: messaoudiachraf/spring-demo:${BUILD_NUMBER}|' deployment.yaml
                        git config user.email 'achmess9@gmail.com'
                        git config user.name 'messaoudi-achraf'
                        git add deployment.yaml
                        git commit -m 'Update image tag to ${BUILD_NUMBER}'
                        git push https://${GIT_USER}:${GIT_PASS}@github.com/messaoudi-achraf/spring-demo-manifests.git main
                    """
                }
            }
        }

    }
}
