pipeline {
    agent any
    stages {

        stage('Test') {
            steps {
                dir('complete') {
                    sh 'mvn test'
                }
            }
        }

        stage('Build') {
            steps {
                dir('complete') {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('complete') {
                    sh "docker build -t messaoudiachraf/spring-demo:${BUILD_NUMBER} ."
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh "docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}"
                    sh "docker push messaoudiachraf/spring-demo:${BUILD_NUMBER}"
                }
            }
        }

        stage('Update Manifest') {
            steps {
                sh "sed -i 's/spring-demo:.*/spring-demo:${BUILD_NUMBER}/' deployment.yaml"
                sh "git config user.email 'achmess9@gmail.com'"
                sh "git config user.name 'messaoudi-achraf'"
                sh "git add deployment.yaml"
                sh "git commit -m 'Update image tag to ${BUILD_NUMBER}'"
                sh "git push origin main"
            }
        }

    }
}
